# Generated by Django 4.2.5 on 2023-09-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='destinations',
            new_name='destination',
        ),
    ]
