# Generated by Django 4.2.5 on 2023-09-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello_app', '0002_rename_destinations_destination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='destination',
            new_name='destinations',
        ),
    ]
