# Generated by Django 4.2.5 on 2023-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello_app', '0003_rename_destination_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='mydestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=250)),
                ('dimg', models.ImageField(upload_to='travello_pics')),
                ('ddesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mypeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('pimg', models.ImageField(upload_to='travello_pics')),
                ('pdesc', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='ddesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='dimg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='dname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='pdesc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='pimg',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='pname',
            new_name='name1',
        ),
    ]
